### PR TITLE
[fixeddata][m]: fixed data and datapackage.json

### PR DESCRIPTION
**Pull request by Mikanebu**
* fixed data:
  * added missing fields for last 2 columns
  * replaced "N.A." for "-" for MinorUnit column since by convention N.A. is not supported format by specification in order to be validated in the front end side. 
* fixed metadata
  * Added field "MinorUnit" into array Fields since it was missed somehow
  * Changed type "string" to "number" for MinorUnit field since numbers are not considered as a string in the front end. Another solution would be to keep "string" type, but to replace all numbers with single quote in order to make them as a "string". 
Tested, published successfully, preview page showed all data without any error.

### CODE REVIEW

**Comment by rufuspollock** [comment]
@Mikanebu can you explain 

> Changed type "string" to "number" for MinorUnit field since numbers are not considered as a string in the front end. Another solution would be to keep "string" type, but to replace all numbers with single quote in order to make them as a "string"

Also, can you make sure you make you also do an update to the generation script https://github.com/datasets/currency-codes/blob/master/scripts/runall.sh so that we have these corrections when we rerun the data scrape (in fact, it is preferable to fix that script and rerun to get the new data rather than fix data directly).

**Comment by Mikanebu** [comment]
@rufuspollock Somehow, when fields type = string, validation from back end works fine, but in showcase page, js library gives an error for numbers in that column(type=string). It happened with other data packages as well.

**Comment by Mikanebu** [comment]
@rufuspollock Totally agree to change the generation script rather than fix data directly. I will take a look.

**Comment by rufuspollock** [comment]
Closing for now as we have conflicts. Please reopen a new PR if appropriate :-)

**Pull request closed without merging**
